Insert the following packages before running the code:
1/ cv2
2/ tqdm
3/ densratio
I

In [1]:
import cv2 # using opencv to process image
from tqdm import tqdm  # use tqdm to know the process of the iteration

import numpy as np
import pandas as pd
import os         
import random
import matplotlib.pyplot as plt

#from densratio import densratio

import time
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils
import random


import glob
from sklearn.preprocessing import StandardScaler
from skimage.feature import hog
from sklearn.model_selection import train_test_split

%matplotlib inline

Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.


In [2]:
train_path = r'C:\Users\phuph\Desktop\Spiderdatabase\spidertrainset'
csv_path = r'C:\Users\phuph\Desktop\Spiderdatabase\spider_csv.csv'
#test_path = 'test'

size_img = 50


In [3]:
""" From the image, record the label either dangerous or non"""
def record_label(image_name):
    label = image_name.split('.')[0]
    if label == 'dangerous':
        return 1
    elif label == 'non':
        return 0

def create_train():

    training_data = []
    for img in tqdm(os.listdir(train_path)):
        path = os.path.join(train_path, img)
        #img_data = cv2.imread(path)
        #img_data = cv2.resize(img_data, (size_img, size_img))
        training_data.append([path, record_label(img)])
    #np.save('train_data.npy', training_data)
    return training_data


In [4]:
train = create_train()

100%|████████████████████████████████████████████████████████████████████████████| 1005/1005 [00:00<00:00, 3985.41it/s]


In [5]:
dangerous = []
non = []
for image in train:
    if image[1] == 0:
        non.append(image[0])
    else:
        dangerous.append(image[0])

In [6]:
'''
These codes are taken from "NikolasEnt - Vehicle Dection and Tracking" to help with feature selection
(https://github.com/NikolasEnt/Vehicle-Detection-and-Tracking/blob/master/VehicheDetect.ipynb)

'''
def get_hog_features(img, orient, pix_per_cell, cell_per_block, vis=False, feature_vec=True):
    if vis == True: # Call with two outputs if vis==True to visualize the HOG
        features, hog_image = hog(img, orientations=orient, 
                                  pixels_per_cell=(pix_per_cell, pix_per_cell),
                                  cells_per_block=(cell_per_block, cell_per_block), 
                                  transform_sqrt=True, 
                                  visualise=vis, feature_vector=feature_vec)
        return features, hog_image
    else:      # Otherwise call with one output
        features = hog(img, orientations=orient, 
                       pixels_per_cell=(pix_per_cell, pix_per_cell),
                       cells_per_block=(cell_per_block, cell_per_block), 
                       transform_sqrt=True, 
                       visualise=vis, feature_vector=feature_vec)
        return features

# Define a function to compute binned color features  
def bin_spatial(img, size=(16, 16)):
    return cv2.resize(img, size).ravel() 

# Define a function to compute color histogram features 
def color_hist(img, nbins=32):
    ch1 = np.histogram(img[:,:,0], bins=nbins, range=(0, 256))[0]#We need only the histogram, no bins edges
    ch2 = np.histogram(img[:,:,1], bins=nbins, range=(0, 256))[0]
    ch3 = np.histogram(img[:,:,2], bins=nbins, range=(0, 256))[0]
    hist = np.hstack((ch1, ch2, ch3))
    return hist


# Define a function to extract features from a list of images
def img_features(feature_image, spatial_feat, hist_feat, hog_feat, hist_bins, orient, 
                        pix_per_cell, cell_per_block, hog_channel):
    file_features = []
    if spatial_feat == True:
        spatial_features = bin_spatial(feature_image, size=spatial_size)
        #print 'spat', spatial_features.shape
        file_features.append(spatial_features)
    if hist_feat == True:
         # Apply color_hist()
        hist_features = color_hist(feature_image, nbins=hist_bins)
        #print 'hist', hist_features.shape
        file_features.append(hist_features)
    if hog_feat == True:
    # Call get_hog_features() with vis=False, feature_vec=True
        if hog_channel == 'ALL':
            hog_features = []
            for channel in range(feature_image.shape[2]):
                hog_features.append(get_hog_features(feature_image[:,:,channel], 
                                        orient, pix_per_cell, cell_per_block, 
                                        vis=False, feature_vec=True))
                hog_features = np.ravel(hog_features)        
        else:
            feature_image = cv2.cvtColor(feature_image, cv2.COLOR_LUV2RGB)
            feature_image = cv2.cvtColor(feature_image, cv2.COLOR_RGB2GRAY)
            hog_features = get_hog_features(feature_image[:,:], orient, 
                            pix_per_cell, cell_per_block, vis=False, feature_vec=True)
                #print 'hog', hog_features.shape
            # Append the new feature vector to the features list
        file_features.append(hog_features)
    return file_features

def extract_features(imgs, color_space='RGB', spatial_size=(32, 32),
                        hist_bins=32, orient=9, 
                        pix_per_cell=8, cell_per_block=2, hog_channel=0,
                        spatial_feat=True, hist_feat=True, hog_feat=True):
    # Create a list to append feature vectors to
    features = []
    # Iterate through the list of images
    for file_p in imgs:
        file_features = []
        image = cv2.imread(file_p)
        # apply color conversion if other than 'RGB'
        if color_space != 'RGB':
            if color_space == 'HSV':
                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
            elif color_space == 'LUV':
                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2LUV)
            elif color_space == 'HLS':
                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2HLS)
            elif color_space == 'YUV':
                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2YUV)
            elif color_space == 'YCrCb':
                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2YCrCb)
        else: feature_image = np.copy(image)      
        file_features = img_features(feature_image, spatial_feat, hist_feat, hog_feat, hist_bins, orient, 
                        pix_per_cell, cell_per_block, hog_channel)
        features.append(np.concatenate(file_features))
        feature_image=cv2.flip(feature_image,1) # Augment the dataset with flipped images
        file_features = img_features(feature_image, spatial_feat, hist_feat, hog_feat, hist_bins, orient, 
                        pix_per_cell, cell_per_block, hog_channel)
        features.append(np.concatenate(file_features))
    return features # Return list of feature vectors

In [8]:
# Define parameters for feature extraction
color_space = 'LUV' # Can be RGB, HSV, LUV, HLS, YUV, YCrCb
orient = 8  # HOG orientations
pix_per_cell = 8 # HOG pixels per cell
cell_per_block = 2 # HOG cells per block
hog_channel = 0 # Can be 0, 1, 2, or "ALL"
spatial_size = (16, 16) # Spatial binning dimensions
hist_bins = 32    # Number of histogram bins
spatial_feat = True # Spatial features on or off
hist_feat = True # Histogram features on or off
hog_feat = True # HOG features on or off

d_features = extract_features(dangerous, color_space=color_space, 
                        spatial_size=spatial_size, hist_bins=hist_bins, 
                        orient=orient, pix_per_cell=pix_per_cell, 
                        cell_per_block=cell_per_block, 
                        hog_channel=hog_channel, spatial_feat=spatial_feat, 
                        hist_feat=hist_feat, hog_feat=hog_feat)
'''
non_features = extract_features(non, color_space=color_space, 
                        spatial_size=spatial_size, hist_bins=hist_bins, 
                        orient=orient, pix_per_cell=pix_per_cell, 
                        cell_per_block=cell_per_block, 
                        hog_channel=hog_channel, spatial_feat=spatial_feat, 
                        hist_feat=hist_feat, hog_feat=hog_feat)
X = np.vstack((d_features, non_features)).astype(np.float64)                        

X_scaler = StandardScaler().fit(X) # Fit a per-column scaler
scaled_X = X_scaler.transform(X) # Apply the scaler to X

#y = np.hstack((np.ones(len(car_features)), np.zeros(len(notcar_features)))) # Define the labels vector
scaled_X '''

C:\Users\phuph\Anaconda3\lib\site-packages\skimage\feature\_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


'\nnon_features = extract_features(non, color_space=color_space, \n                        spatial_size=spatial_size, hist_bins=hist_bins, \n                        orient=orient, pix_per_cell=pix_per_cell, \n                        cell_per_block=cell_per_block, \n                        hog_channel=hog_channel, spatial_feat=spatial_feat, \n                        hist_feat=hist_feat, hog_feat=hog_feat)\nX = np.vstack((d_features, non_features)).astype(np.float64)                        \n\nX_scaler = StandardScaler().fit(X) # Fit a per-column scaler\nscaled_X = X_scaler.transform(X) # Apply the scaler to X\n\n#y = np.hstack((np.ones(len(car_features)), np.zeros(len(notcar_features)))) # Define the labels vector\nscaled_X '

In [9]:
d_features

[array([  1.40000000e+02,   8.20000000e+01,   9.50000000e+01, ...,
          4.39746290e-02,   3.35998597e-02,   2.59593030e-02]),
 array([  1.15000000e+02,   8.30000000e+01,   8.70000000e+01, ...,
          1.82358102e-02,   2.43207050e-02,   2.86319773e-02]),
 array([  2.11000000e+02,   1.04000000e+02,   1.41000000e+02, ...,
          3.92407161e-02,   5.55663138e-02,   1.02751869e-02]),
 array([  1.95000000e+02,   1.04000000e+02,   1.42000000e+02, ...,
          1.42428348e-02,   6.39441456e-03,   6.63840624e-03]),
 array([  1.14000000e+02,   9.80000000e+01,   1.34000000e+02, ...,
          6.67066611e-02,   2.36732453e-02,   1.25688941e-02]),
 array([  1.14000000e+02,   9.00000000e+01,   1.22000000e+02, ...,
          1.43013761e-02,   4.26196278e-02,   6.49160196e-02]),
 array([  2.35000000e+02,   9.70000000e+01,   1.36000000e+02, ...,
          0.00000000e+00,   2.23952597e-02,   0.00000000e+00]),
 array([  2.36000000e+02,   9.70000000e+01,   1.36000000e+02, ...,
          0.0000

In [5]:
A_train = []
for i in train:
    a = i[0].reshape(-1)
    A_train.append(a)
A_train = np.asarray(A_train)
B_train = np.asarray([i[1] for i in train])

In [6]:
indices = np.arange(A_train.shape[0])
from sklearn.cross_validation import train_test_split
X_train0, X_test0, Y_train, Y_test,idx1,idx2 = train_test_split(A_train, B_train,indices, test_size=0.2, random_state=0)

C:\Users\phuph\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:

scaler = StandardScaler()
X_train1 = scaler.fit_transform(X_train0)
X_test1 = scaler.fit_transform(X_test0)

pca = PCA(n_components=20)
X_train = pca.fit_transform(X_train1)
X_test= pca.transform(X_test1)


In [8]:
import random
rho_po_list = [0.1,0.2,0.3,0.4,0.4]
rho_ne_list = [0.3,0.1,0.4,0.1,0.4]
Y_new_list = []
for i in range(5):
    rho_po = rho_po_list[i]
    rho_ne = rho_ne_list[i]
    Y_temp = np.copy(Y_train)
    for j in range(len(Y_temp)):
        if Y_train[j] ==1:
            temp = random.random()
            if temp < rho_po:
                Y_temp[j] = 0
        else:
            t = random.random()
            if t < rho_ne:
                Y_temp[j] = 1
    Y_new_list.append([Y_temp,rho_po,rho_ne])
'''
Y_new_list = []
for i in range(5):
    rho_po = random.choice(rho_po_list)
    rho_ne = random.choice(rho_ne_list)
    Y_temp = Y_train * (np.cumsum(Y_train) <= (1 - rho_po) * sum(Y_train))
    s = 1 - (1 - Y_train) * (np.cumsum(1 - Y_train) <= (1 - rho_ne) * sum(1 - Y_train))
    Y_temp[Y_train==0] = s[Y_train==0]
    Y_new_list.append([Y_temp,rho_po,rho_ne])
'''

'\nY_new_list = []\nfor i in range(5):\n    rho_po = random.choice(rho_po_list)\n    rho_ne = random.choice(rho_ne_list)\n    Y_temp = Y_train * (np.cumsum(Y_train) <= (1 - rho_po) * sum(Y_train))\n    s = 1 - (1 - Y_train) * (np.cumsum(1 - Y_train) <= (1 - rho_ne) * sum(1 - Y_train))\n    Y_temp[Y_train==0] = s[Y_train==0]\n    Y_new_list.append([Y_temp,rho_po,rho_ne])\n'

In [9]:
import rpy2
import rpy2.robjects as robjects
r = robjects.r
#from rpy2.robjects.packages import importr
#utils = importr("densratio")
import rpy2.robjects.numpy2ri as numpy2ri
rpy2.robjects.numpy2ri.activate()

robjects.r('''
           f <- function(t,t1) {

                    library(densratio)
                    dens <- densratio(x = t, y = t1, method = "KLIEP")
                    result <-dens$compute_density_ratio(t1)
            }
            ''')
kliep_check = robjects.globalenv['f']

In [10]:
### Estimate the noise rate###
def KLIEP_e(X,Y):
    e_list=[]
    X_rho_po= X[Y ==1]
    X_rho_ne= X[Y ==0]
    result_po= kliep_check(X_rho_po,X)
    result_ne= kliep_check(X_rho_ne,X)
    Po = np.asarray(result_po)
    Ne = np.asarray(result_ne)
    n = len(X)
    py_po = sum(1 for i in Y if i==1)/n
    py_ne = sum(1 for i in Y if i==0)/n
    Po_n = min(Po*py_po)
    Ne_n = min(Ne*py_ne)
    e_list.append([Ne_n,Po_n])
    return e_list
    

In [11]:
### Estimate the noise rate###
count =0
for i in Y_new_list:
    a = KLIEP_e(X_train,i[0])
    print(count,i[1],i[2],a)
    count = count +1

0 0.1 0.3 [[0.2596719578146986, 0.33533738638873317]]
1 0.2 0.1 [[0.38371144928449974, 0.22134167674421007]]
2 0.3 0.4 [[0.30488436530293855, 0.3082745739294161]]
3 0.4 0.1 [[0.50103661922822973, 0.13669309829085971]]
4 0.4 0.4 [[0.40422633995262341, 0.30335501021150235]]


In [ ]:
def KLIEP_betas(X,Y):
    e_list=[]
    X_rho_po= X[Y ==1]
    X_rho_ne= X[Y ==0]
    result_po= kliep_check(X_rho_po,X)
    result_ne= kliep_check(X_rho_ne,X)
    Po = np.asarray(result_po)
    Ne = np.asarray(result_ne)
    n = len(X)
    py_po = sum(1 for i in Y if i==1)/n
    py_ne = sum(1 for i in Y if i==0)/n
    Po_n = min(Po*py_po)
    Ne_n = min(Ne*py_ne)
    betas = np.ones((n,), dtype = None)
    for i in range(n):
        if Y[i] == 0:
            if Po[i] == 0:
                betas[i] = 0
            else:
                betas[i] = (Po[i]*py_po - Po_n)/ ((1-Po_n-Ne_n)*Po[i]*py_po)
        else: 
            if Ne[i] == 0:
                betas[i] =0
            else:
                betas[i] = (Ne[i]*py_ne - Ne_n)/ ((1-Po_n-Ne_n)*Ne[i]*py_ne)

    return betas    

In [ ]:

dims = X_train.shape[1]
n_y = 2
print( 'Number of features: %d ' %dims)
print( 'Number of classes: %d' %n_y)
print("Building model...")

model = Sequential()
model.add(Dense(80, input_shape=(dims,)))
model.add(Dense(60, input_shape=(dims,)))
model.add(Dense(40, input_shape=(dims,)))
model.add(Dense(n_y, input_shape=(dims,)))
model.add(Activation('softmax'))
model.compile(optimizer='sgd', loss='categorical_crossentropy',sample_weight_mode=None,metrics=['accuracy'])


In [ ]:
## Accuracy for baseline flipped dataset - noisy#
accuracy_list =[]
count =0
for i in Y_new_list:
    y= np_utils.to_categorical(i[0], 2)
    model.fit(X_train,y, verbose=1,epochs=1)
    pred = model.predict_classes(X_test)
    a = accuracy_score(Y_test,pred)
    accuracy_list.append([count,a,i[1],i[2]])
    count = count +1
for i in accuracy_list:
    print(i)

In [ ]:
## Accuracy for auto without RANDOM-using KLIEP to estimate noise ###
accuracy_list =[]
for i in Y_new_list:
    rho_po_max = i[1]
    rho_ne_max = i[2]
    X_rho_po= X_train[i[0] ==1]
    result_po= kliep_check(X_rho_po,X_train)
    Po = np.asarray(result_po)
    n = len(X_train)
    py_po = sum(1 for z in i[0]  if z==1)/n
    eta_po = Po*py_po

    St = []
    distill_ind = []
    for t in range(n):
        if eta_po[t] > ((1+rho_ne_max)/2):
            St.append([X_train[t],1])
            distill_ind.append([idx1[t],1])

        elif eta_po [t]  < ((1-rho_po_max)/2):
            St.append([X_train[t],0])
            distill_ind.append([idx1[t],0])
    St.append([X_train[1],1])
    St.append([X_train[1],0])
    St_x =np.asarray([i[0] for i in St])
    St_y =np.asarray([i[1] for i in St])
    print(St_y)
    count =0
    y= np_utils.to_categorical(St_y, 2)
    model.fit(St_x,y, verbose=1,epochs=1)
    pred = model.predict_classes(X_test)
    a = accuracy_score(Y_test,pred)
    accuracy_list.append([count,a,i[1],i[2]])
    count = count +1
    
for i in accuracy_list:
    print(i)

        

In [ ]:
# Accuracy - auto without random with LR estimate##
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty="l2")

accuracy_list =[]
for i in Y_new_list:
    r = [0.1, 0.2, 0.3, 0.4]
    rho_po_max = i[1]
    rho_ne_max = i[2]
    n = len(X_train)
    clf.fit(X_train,i[0])
    e = clf.predict_proba(X_train)
    eta_po = np.asarray([i[1] for i in e])
    St = []
    St_n=[]
    distill_ind = []

    for t in range(n):
        if eta_po[t] > ((1+rho_ne_max)/2):
            St.append([X_train[t],1])
            distill_ind.append([idx1[t],1])

        elif eta_po [t]  < ((1-rho_po_max)/2):
            St.append([X_train[t],0])
            distill_ind.append([idx1[t],0])
        else: 
            St_n.append([X_train[t],Y_train[t]])
    
      
    St_x =np.asarray([i[0] for i in St])
    St_y =np.asarray([i[1] for i in St])
    
    print(St_y)
    
    count =0
    sample_weight = KLIEP_betas(St_x,St_y)
    y= np_utils.to_categorical(St_y, 2)
    model.fit(St_x,y,sample_weight=sample_weight,verbose=1,epochs=1)
    pred = model.predict_classes(X_test)
    a = accuracy_score(Y_test,pred)
    accuracy_list.append([count,a,rho_po_max,rho_ne_max])
    count = count +1
    
for i in accuracy_list:
    print(i)

In [ ]:
## Accuracy for auto WITH RANDOM - using LR to estimate noise ###

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty="l2")

accuracy_list =[]
for i in Y_new_list:
    r = [0.1, 0.2, 0.3, 0.4]
    rho_po_max = i[1]
    rho_ne_max = i[2]
    n = len(X_train)
    clf.fit(X_train,i[0])
    e = clf.predict_proba(X_train)
    eta_po = np.asarray([i[1] for i in e])
    St = []
    St_n=[]
    distill_ind = []

    for t in range(n):
        if eta_po[t] > ((1+rho_ne_max)/2):
            St.append([X_train[t],1])
            distill_ind.append([idx1[t],1])

        elif eta_po [t]  < ((1-rho_po_max)/2):
            St.append([X_train[t],0])
            distill_ind.append([idx1[t],0])
        else: 
            St_n.append([X_train[t],Y_train[t]])
    
    q = 0
    while (q<20):
        z = random.randint(0,len(St_n))
        St.append(St_n[z])
        q = q+1
    
      
    St_x =np.asarray([i[0] for i in St])
    St_y =np.asarray([i[1] for i in St])
    
    print(St_y)
    
    count =0
    sample_weight = KLIEP_betas(St_x,St_y)
    y= np_utils.to_categorical(St_y, 2)
    model.fit(St_x,y,sample_weight=sample_weight,verbose=1,epochs=1)
    pred = model.predict_classes(X_test)
    a = accuracy_score(Y_test,pred)
    accuracy_list.append([count,a,rho_po_max,rho_ne_max])
    count = count +1
    
for i in accuracy_list:
    print(i)


In [ ]:
## Accuracy Rater Label using KLIEP"
from sklearn.model_selection import StratifiedKFold

accuracy_list =[]
df_noise = pd.read_csv(csv_path)
C_train = np.asarray(df_noise["Rater label"])

skf = StratifiedKFold(n_splits=10)
for train_index,test_index in skf.split(A_train,C_train,B_train):
    X_train0, X_test0 = A_train[train_index], A_train[test_index]
    Y_train, Y_test = C_train[train_index], C_train[test_index]
    BB_train, BB_test = B_train[train_index], B_train[test_index]
    idx1= train_index
    X_train1 = scaler.fit_transform(X_train0)
    X_test1 = scaler.fit_transform(X_test0)

    X_train = pca.fit_transform(X_train1)
    X_test= pca.transform(X_test1)

    r = [0.1,0.15, 0.2, 0.25, 0.3,0.35, 0.4, 0.45]
    #rho_po_max = 0.2
    #rho_ne_max = 0.45
    rho_po_max = random.choice(rho_po_list)
    rho_ne_max = random.choice(rho_ne_list)
    X_rho_po= X_train[Y_train ==1]
    result_po= kliep_check(X_rho_po,X_train)
    Po = np.asarray(result_po)
    n = len(X_train)
    py_po = sum(1 for z in Y_train if z==1)/n
    eta_po = Po*py_po

    St = []
    St_n=[]
    distill_ind = []

    for t in range(n):
        if eta_po[t] > ((1+rho_ne_max)/2):
            St.append([X_train[t],1])
            distill_ind.append([idx1[t],1])

        elif eta_po [t]  < ((1-rho_po_max)/2):
            St.append([X_train[t],0])
            distill_ind.append([idx1[t],0])
        else: 
            St_n.append([X_train[t],BB_train[t]])


    q = 0
    while (q<20):
        z = random.randint(0,len(St_n))
        St.append(St_n[z])
        q = q+1

    St_x =np.asarray([t[0] for t in St])
    St_y =np.asarray([t[1] for t in St])
    print(St_y)
    sample_weight = KLIEP_betas(St_x,St_y)
    y= np_utils.to_categorical(St_y, 2)
    model.fit(St_x,y,sample_weight=sample_weight,verbose=1,epochs=1)
    pred = model.predict_classes(X_test)
    a = accuracy_score(Y_test,pred)
    accuracy_list.append([a])

print(np.mean(accuracy_list,axis=0),np.std(accuracy_list,axis=0))

In [ ]:
###Accuracy on spiderdataset with instance class dependent using LR ##3
from sklearn.model_selection import StratifiedKFold

accuracy_list =[]
df_noise = pd.read_csv(csv_path)
C_train = np.asarray(df_noise["Rater label"])

skf = StratifiedKFold(n_splits=10)
for train_index,test_index in skf.split(A_train,C_train,B_train):
    X_train0, X_test0 = A_train[train_index], A_train[test_index]
    Y_train, Y_test = C_train[train_index], C_train[test_index]
    BB_train, BB_test = B_train[train_index], B_train[test_index]
    idx1= train_index
    X_train1 = scaler.fit_transform(X_train0)
    X_test1 = scaler.fit_transform(X_test0)

    X_train = pca.fit_transform(X_train1)
    X_test= pca.transform(X_test1)

    r = [0.1,0.15, 0.2, 0.25, 0.3,0.35, 0.4, 0.45]
    #rho_po_max = 0.2
    #rho_ne_max = 0.45
    rho_po_max = random.choice(rho_po_list)
    rho_ne_max = random.choice(rho_ne_list)
    n = len(X_train)
    clf.fit(X_train,Y_train)
    e = clf.predict_proba(X_train)
    eta_po = np.asarray([i[1] for i in e])
    
    St = []
    St_n=[]
    distill_ind = []

    for t in range(n):
        if eta_po[t] > ((1+rho_ne_max)/2):
            St.append([X_train[t],1])
            distill_ind.append([idx1[t],1])

        elif eta_po [t]  < ((1-rho_po_max)/2):
            St.append([X_train[t],0])
            distill_ind.append([idx1[t],0])
        else: 
            St_n.append([X_train[t],BB_train[t]])


    q = 0
    while (q<20):
        z = random.randint(0,len(St_n))
        St.append(St_n[z])
        q = q+1

    St_x =np.asarray([t[0] for t in St])
    St_y =np.asarray([t[1] for t in St])
    print(St_y)
    sample_weight = KLIEP_betas(St_x,St_y)
    y= np_utils.to_categorical(St_y, 2)
    model.fit(St_x,y,sample_weight=sample_weight,verbose=1,epochs=1)
    pred = model.predict_classes(X_test)
    a = accuracy_score(Y_test,pred)
    accuracy_list.append([a])

print(np.mean(accuracy_list,axis=0),np.std(accuracy_list,axis=0))

In [ ]:
### FOR AUTO USING ACTIVE LEARNING FOR FLIPPED DATASET  ###

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty="l2")

accuracy_list =[]
for i in Y_new_list:
    r = [0.1, 0.2, 0.3, 0.4]
    rho_po_max = i[1]
    rho_ne_max = i[2]
    n = len(X_train)
     
    clf.fit(X_train,i[0])
    e = clf.predict_proba(X_train)
    eta_po = np.asarray([i[1] for i in e])
    d = clf.decision_function(X_train)

    St = []
    St_n=[]
    St_d=[]
    distill_ind = []

    for t in range(n):
        if eta_po[t] > ((1+rho_ne_max)/2):
            St.append([X_train[t],1])
            distill_ind.append([idx1[t],1])

        elif eta_po [t]  < ((1-rho_po_max)/2):
            St.append([X_train[t],0])
            distill_ind.append([idx1[t],0])
        else: 
            St_n.append([X_train[t],Y_train[t]])
            St_d.append(d[t])
    dist = np.abs(St_d)
    a = dist.argsort()[:20]
    for z in a:
        St.append(St_n[z])
    
    St_x =np.asarray([i[0] for i in St])
    St_y =np.asarray([i[1] for i in St])
    
    print(St_y)
    count =0
    sample_weight = KLIEP_betas(St_x,St_y)
    y= np_utils.to_categorical(St_y, 2)
    model.fit(St_x,y,sample_weight=sample_weight,verbose=1,epochs=1)
    pred = model.predict_classes(X_test)
    a = accuracy_score(Y_test,pred)
    accuracy_list.append([count,a,rho_po_max,rho_ne_max])
    count = count +1
    
for i in accuracy_list:
    print(i)


In [ ]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty="l2")

from sklearn.model_selection import StratifiedKFold

accuracy_list =[]
df_noise = pd.read_csv(csv_path)
C_train = np.asarray(df_noise["Rater label"])

skf = StratifiedKFold(n_splits=10)
for train_index,test_index in skf.split(A_train,C_train, B_train):
    X_train0, X_test0 = A_train[train_index], A_train[test_index]
    Y_train, Y_test = C_train[train_index], C_train[test_index]
    BB_train, BB_test = B_train[train_index], B_train[test_index]
    idx1= train_index
    X_train1 = scaler.fit_transform(X_train0)
    X_test1 = scaler.fit_transform(X_test0)

    X_train = pca.fit_transform(X_train1)
    X_test= pca.transform(X_test1)

    r = [0.1,0.15, 0.2, 0.25, 0.3,0.35, 0.4, 0.45]
    rho_po_max = random.choice(rho_po_list)
    rho_ne_max = random.choice(rho_ne_list)
    n = len(X_train)
    clf.fit(X_train,Y_train)
    e = clf.predict_proba(X_train)
    eta_po = np.asarray([i[1] for i in e])
    d = clf.decision_function(X_train)
        
    
    St = []
    St_n=[]
    distill_ind = []
    St_d=[]

    for t in range(n):
        if eta_po[t] > ((1+rho_ne_max)/2):
            St.append([X_train[t],1])
            distill_ind.append([idx1[t],1])

        elif eta_po [t]  < ((1-rho_po_max)/2):
            St.append([X_train[t],0])
            distill_ind.append([idx1[t],0])
        else: 
            St_n.append([X_train[t],BB_train[t]])
            St_d.append(d[t])

    dist = np.abs(St_d)
    a = dist.argsort()[:20]
    for z in a:
        St.append(St_n[z])
   

    St_x =np.asarray([t[0] for t in St])
    St_y =np.asarray([t[1] for t in St])
    print(St_y)
    sample_weight = KLIEP_betas(St_x,St_y)
    y= np_utils.to_categorical(St_y, 2)
    model.fit(St_x,y,sample_weight=sample_weight,verbose=1,epochs=1)
    pred = model.predict_classes(X_test)
    a = accuracy_score(Y_test,pred)
    accuracy_list.append([a])

print(np.mean(accuracy_list,axis=0),np.std(accuracy_list,axis=0))

In [ ]:
colors = ['steelblue' if label == 1 else 'darkred' for label in y]
plt.scatter(X[:,0], X[:,1], color=colors)
y.shape, X.shape